### ISSUE TITLE
Factorio game freezes when selecting large power pole or substation

### ISSUE THREAD

**Issue by ajklotz** [Xcone/factorio_pump#18]
Run the PUMP tool over a fissure, select one of the large power poles and press confirm, game freezes. 

https://drive.google.com/file/d/1PF1CYYj78lmumyGcozrkdC85RXC98HfI/view?usp=sharing

![image](https://user-images.githubusercontent.com/9448682/226037472-267f23f9-7ac7-4290-842a-171fa53fa6ce.png)

**Comment by Xcone** [comment]
Hi! As mentioned on the mod portal: Succesful reproduction and fix in 1.3.2

Thanks again for reporting and sharing a save. Very helpful :-)
