### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by johnptr126** [Xcone/factorio_pump#19]
Place pumps as a user so I do not get pumpjack has no last_user error
![factorio_mIZdUXw5Kl](https://github.com/Xcone/factorio_pump/assets/95537825/6020186a-1fc0-493a-bcc8-23d929250dde)

Ability to place pumpjacks without pipes, just jacks and poles please.

Thank you.

**Comment by Xcone** [comment]
Hi, can you elaborate when you get that error? I've never seen it before. Could it be related to another mod?

Also, why would you want to skip the pipes? The whole point of P.U.M.P. is to avoid having to place pipes. Can you explain more of how you're playing and why it would make sense to you to support that?

**Comment by johnptr126** [comment]
> Hi, can you elaborate when you get that error? I've never seen it before. Could it be related to another mod?
> 
> Also, why would you want to skip the pipes? The whole point of P.U.M.P. is to avoid having to place pipes. Can you explain more of how you're playing and why it would make sense to you to support that?

Hello,
I'm using [auto resource mod ](https://mods.factorio.com/mod/auto-resource) which grabs resources directly without needing pipes. It seems that mod doesnt work if its not placed by "user" but I've solved this issue by using similar mod to yours called Well Planner and it does place jacks as user so that solves my issue.
Thanks for fast reply anyways.

**Comment by Xcone** [comment]
Ok, thanks you for explaining more. I'll have a look at the mod you mentioned later and consider changing P.U.M.P. 

Will be a while as I'm on a long holiday right now. But it seems you're set for now, anyway. 🙂

**Comment by Xcone** [comment]
I am going to assume this is fixed. Other changes have been made involving passing the player or their force to the build action. In the meantime Factorio 2.0 also had API changes that mandated some things in this area too.

As I havent tested it with the mod in question, I can't be certain though.
