### ISSUE TITLE
Switch Deconstruct to Use find_entities_filtered Based on Extractor Collision Mask

### ISSUE THREAD

**Issue by randomflyingtaco** [Xcone/factorio_pump#28]
https://github.com/Xcone/factorio_pump/blob/b6ee33509d6b27f030dc106cf684c80b9504c6a0/mod/constructor.lua#L84

This would be helpful when using modded mining drills that have non-default collision masks, in particular Tiberium Spikes from **https://mods.factorio.com/mod/Factorio-Tiberium**

I can submit this as a pull request if you accept those

**Comment by Xcone** [comment]
Taking the collision mask into account sounds like a good improvement.

I do accept pull requests (within reason, ofc).

**Comment by Xcone** [comment]
Did a quick test on vulcanus. Seems rubble still gets deconstructed as it was. So I am satisfied with the the change you offered. 

I did not test with the tiberium mod. I assume you already did that as you knew the change to make? If not, you can do so now, as I uploaded 2.1.3 to the mod portal that contains your change.

Always nice to improve on mod compatibility, without doing "specials". Thank you for the improvement. 👍

**Comment by randomflyingtaco** [comment]
Tested locally to confirm that fix worked for Tiberium before submitting pull request. 
I had introduced cliffs with limited collision to our oil-deposit-like resources to give players the ability to deconstruct them with special cliff explosives, but because of this the deconstruction order for PUMP was destroying the resources before placing the custom pumpjacks.
