### ISSUE TITLE
Support other pipes

### ISSUE THREAD

**Issue by yaSebastian** [Xcone/factorio_pump#4]
Hi,

as requested, here's the uploaded file.
[Temp PUMP.zip](https://github.com/Xcone/factorio_pump/files/5760511/Temp.PUMP.zip)

To make it as simple as possible, I've done the following
- Removed all mods except a bare minimum. The following are still present:
  - Krastorio 2 for the steel pipes
  - Creative mod for efficiency
    - Increased walking speed
    - Ghosts are spawned automatically when placed, no building required, no materials required
    - Instant crafting without materials
    - Instant research
    - Creative mod should be possible to be removed without any issues, revoking most of the changes I set up.
  - Improved Research Queue for getting the required research more easily
    - Should cause no issues when removing
  - Accompanying library mods
- Researched all the necessary technologies
- Picked an oil field and set it up the way it should be done when the pipes become available
- Set up Roboports and Electricity around it
- Gave you the best armor with Roboports, Solar, etc.
  - Added the best available energy generators. In Krastorio 2 they all need feul, theoretically, they should last you days, but if they run out, you have additional fuel in your inventory. To use it, open your equipment grid, right click the reactors, you can fill them like vehicles then
- Filled your inventory with pumps and pipes of both kinds as well as roboports
- Created 3 Upgrade plans for you to experiment with
  - Upgrade iron to steel (pipes and pumps)
  - Downgrade steel to iron (pipes and pumps)
  - A regular unmodified upgrade plan to see how iron gets upgraded to steel
 
I hope this makes it as simple as possible for you.

Cheers
Sebastian

**Comment by Xcone** [comment]
Fixed in 1.0.2
